### ISSUE TITLE
Move to Fly.io

### ISSUE THREAD

**Issue by LitoMore** [LitoMore/simple-icons-cdn#10]
We're planning to move this service from Vercel to Fly.io.

The code is ready on the https://github.com/LitoMore/simple-icons-cdn/tree/main branch.

### Todo

- [x] Setup Fly.io app (https://simple-icon-cdn.fly.dev) (@LitoMore)
- [x] Move domain `icons.ly` from Vercel to Fly.io (@LitoMore)
- [x] Update domain `cdn.simpleicons.org` DNS (@mondeja)
- [x] Move domain `cdn.simpleicons.org` from Vercel to Fly.io (@LitoMore)
- [x] Add Fly.io icon to Simple Icons (https://github.com/simple-icons/simple-icons/pull/11025) (@LitoMore)

**Comment by artbindu** [comment]
Lots of icons are not wokring now as follows:

https://cdn.simpleicons.org/AzureDevOps
https://cdn.simpleicons.org/windows
https://cdn.simpleicons.org/VisualStudioCode
https://cdn.simpleicons.org/azuredevops


What is solution for it ?

**Comment by LitoMore** [comment]
@artbindu See https://github.com/simple-icons/simple-icons/issues/11236.
